// generated by gen.py
#pragma once
#include "dgint8_args.h"
void dgint8_run_0(const dgint8::Args& args);
void dgint8_run_1(const dgint8::Args& args);
void dgint8_run_2(const dgint8::Args& args);
void dgint8_run_3(const dgint8::Args& args);
void dgint8_run_4(const dgint8::Args& args);
void dgint8_run_5(const dgint8::Args& args);
void dgint8_run_6(const dgint8::Args& args);
void dgint8_run_7(const dgint8::Args& args);
void dgint8_run_8(const dgint8::Args& args);
void dgint8_run_9(const dgint8::Args& args);
void dgint8_run_10(const dgint8::Args& args);
void dgint8_run_11(const dgint8::Args& args);
void dgint8_run_12(const dgint8::Args& args);
void dgint8_run_13(const dgint8::Args& args);
void dgint8_run_14(const dgint8::Args& args);
void dgint8_run_15(const dgint8::Args& args);
void dgint8_run_16(const dgint8::Args& args);
void dgint8_run_17(const dgint8::Args& args);
void dgint8_run_18(const dgint8::Args& args);
void dgint8_run_19(const dgint8::Args& args);
void dgint8_run_20(const dgint8::Args& args);
void dgint8_run_21(const dgint8::Args& args);
void dgint8_run_22(const dgint8::Args& args);
void dgint8_run_23(const dgint8::Args& args);
void dgint8_run_24(const dgint8::Args& args);
void dgint8_run_25(const dgint8::Args& args);
void dgint8_run_26(const dgint8::Args& args);
void dgint8_run_27(const dgint8::Args& args);
void dgint8_run_28(const dgint8::Args& args);
void dgint8_run_29(const dgint8::Args& args);
static const dgint8::CfgInfo kDgInt8Cfgs[] = {
    {256, 128, 3, 2, 1, 0, 0, 256, 0, "256x128 s3 c1x2"},
    {256, 128, 3, 1, 0, 0, 0, 256, 0, "256x128 s3 c1x1"},
    {128, 64, 8, 1, 0, 0, 0, 256, 0, "128x64 s8 c1x1"},
    {128, 128, 5, 1, 0, 0, 0, 256, 0, "128x128 s5 c1x1"},
    {128, 128, 5, 2, 0, 0, 0, 256, 0, "128x128 s5 c2x1"},
    {128, 192, 4, 2, 1, 0, 0, 256, 0, "128x192 s4 c1x2"},
    {64, 128, 8, 1, 0, 0, 0, 128, 0, "64x128 s8 c1x1"},
    {256, 96, 3, 2, 1, 0, 0, 256, 0, "256x96 s3 c1x2"},
    {256, 128, 3, 2, 1, 4096, 4096, 256, 0, "256x128 s3 c1x2 N4096K4096"},
    {256, 128, 3, 2, 1, 1024, 4096, 256, 0, "256x128 s3 c1x2 N1024K4096"},
    {256, 128, 3, 2, 1, 12288, 4096, 256, 0, "256x128 s3 c1x2 N12288K4096"},
    {256, 128, 3, 2, 1, 4096, 12288, 256, 0, "256x128 s3 c1x2 N4096K12288"},
    {256, 128, 3, 1, 0, 4096, 4096, 256, 0, "256x128 s3 c1x1 N4096K4096"},
    {256, 128, 3, 1, 0, 1024, 4096, 256, 0, "256x128 s3 c1x1 N1024K4096"},
    {256, 128, 3, 1, 0, 12288, 4096, 256, 0, "256x128 s3 c1x1 N12288K4096"},
    {256, 128, 3, 1, 0, 4096, 12288, 256, 0, "256x128 s3 c1x1 N4096K12288"},
    {128, 64, 8, 1, 0, 1024, 4096, 256, 0, "128x64 s8 c1x1 N1024K4096"},
    {128, 128, 5, 2, 1, 4096, 4096, 256, 0, "128x128 s5 c1x2 N4096K4096"},
    {128, 128, 5, 2, 0, 4096, 4096, 256, 0, "128x128 s5 c2x1 N4096K4096"},
    {128, 128, 5, 2, 1, 4096, 4096, 256, 0, "128x128 s5 c1x2 N4096K4096 DB"},
    {128, 128, 5, 2, 0, 4096, 4096, 256, 0, "128x128 s5 c2x1 N4096K4096 DB"},
    {128, 128, 5, 1, 0, 4096, 4096, 256, 0, "128x128 s5 c1x1 N4096K4096 DB"},
    {128, 128, 4, 2, 1, 4096, 4096, 256, 0, "128x128 s4 c1x2 N4096K4096 DB"},
    {128, 128, 5, 2, 1, 12288, 4096, 256, 0, "128x128 s5 c1x2 N12288K4096 DB"},
    {128, 128, 5, 2, 1, 4096, 12288, 256, 0, "128x128 s5 c1x2 N4096K12288 DB"},
    {128, 128, 5, 2, 1, 1024, 4096, 256, 0, "128x128 s5 c1x2 N1024K4096 DB"},
    {128, 64, 8, 1, 0, 1024, 4096, 256, 0, "128x64 s8 c1x1 N1024K4096 DB"},
    {64, 128, 8, 1, 0, 0, 0, 128, 0, "64x128 s8 c1x1 DB"},
    {128, 128, 5, 1, 0, 0, 0, 256, 0, "128x128 s5 c1x1 DB"},
    {128, 128, 5, 2, 1, 0, 0, 256, 0, "128x128 s5 c1x2 DB"},
};
typedef void (*dgint8_run_fn)(const dgint8::Args&);
static const dgint8_run_fn kDgInt8Runs[] = {
    dgint8_run_0,
    dgint8_run_1,
    dgint8_run_2,
    dgint8_run_3,
    dgint8_run_4,
    dgint8_run_5,
    dgint8_run_6,
    dgint8_run_7,
    dgint8_run_8,
    dgint8_run_9,
    dgint8_run_10,
    dgint8_run_11,
    dgint8_run_12,
    dgint8_run_13,
    dgint8_run_14,
    dgint8_run_15,
    dgint8_run_16,
    dgint8_run_17,
    dgint8_run_18,
    dgint8_run_19,
    dgint8_run_20,
    dgint8_run_21,
    dgint8_run_22,
    dgint8_run_23,
    dgint8_run_24,
    dgint8_run_25,
    dgint8_run_26,
    dgint8_run_27,
    dgint8_run_28,
    dgint8_run_29,
};
static const int kDgInt8NumCfgs = 30;
