"""Generate the math-warpgroup ping-pong ("PP", approach C) variant of the INT8 1D2D kernel:
  include/deep_gemm/impls/sm90_int8_gemm_1d2d_pp.cuh  (kernel `sm90_int8_gemm_1d2d_pp_impl`, derived from the generated
                                                        sm90_int8_gemm_1d2d.cuh by checked string edits)
  launcher_pp.cuh                                      (`dgint8::launch_pp<..., kPPMode>`, derived from launcher.cuh)

Idea (CUTLASS KernelTmaWarpSpecializedPingpong / OrderedSequenceBarrier<1,2>, applied per WGMMA batch instead of per tile):
the mainloop of each math warpgroup is the exact default sequence (full_barrier wait -> scales -> arrive -> 4x wgmma -> commit ->
wait<0> -> empty arrive -> promote, ONE int32 accumulator per warpgroup), but the two math warpgroups are forced to issue their
WGMMA batches strictly alternately: WG0 batch b, WG1 batch b, WG0 batch b+1, ... A single warpgroup's batch keeps all 4 tensor
cores of the SM busy, so while WG0 promotes (64 I2F + 64 FFMA per thread on the CUDA cores) the tensor cores execute WG1's batch,
and vice versa; in the default kernel both warpgroups promote at the same time and the tensor cores idle.
Ordering = two named barriers (hw ids 10/11; the kernel uses 0 (__syncthreads), 8 and 9): warpgroup w does `bar.arrive bar[w], 256`
after its commit, the other warpgroup does `bar.sync bar[w], 256` before its own issue.
  kPPMode 1: WG0 syncs on bar[1] right AFTER its own signal (uniform per batch, nothing to special-case at tile boundaries);
  kPPMode 2: both sync BEFORE issuing, WG0 skips only the very first wait of the kernel and consumes WG1's last signal at the end.
No accumulator is read while its own wgmma group is in flight (same as the default kernel), so ptxas has no C7514 reason to
serialize; per-element math and k order are unchanged -> bit-identical to the default kernel. Works for BLOCK_M = 128 (one 64-row
wave per warpgroup, handshake per k-block) and BLOCK_M = 256 (two waves per warpgroup, handshake per wave = per 4 wgmma).
The default kernel / launcher / configs 0-29 are untouched. Re-run after editing this file (after gen_kernel.py).

RESULTS (H100, logs/pp_time{1,2,3,4}.log, results/int8_g128_pp_parts/): every mode is bit-identical to the default kernel
(267 / 267 checks incl. K=128/256/384, M=901/1802), 168 registers, no C7514, no spills (shape-compiled cfgs).
  * modes 1/2 (issue-order alternation): 128x128 == lockstep default (~990 cycles per k-block at 4096^3: the tensor cores arbitrate the
    two in-flight chains fairly, both batches finish together, both warpgroups still promote at the same time); 256x128 +3-4% vs the
    default 256x128 (1099-1106 vs 1062 TFLOPS at 4096^3, 1105 vs 1061-1071 at 12288x4096x4096, 1103 vs 1070 at 4096x12288x42240) but
    below the DB kernel at 4096^3 (1141).
  * modes 5/6/7 (true tensor-core mutual exclusion, +- dual chain): 940-965 at 4096^3 -- ONE warpgroup alone on the tensor cores only
    reaches ~57% of the SM peak (~500 cycles per 64x128x128 batch), with one or two independent chains alike; two concurrent warpgroups
    are needed for full rate, so per-batch ping-pong cannot hide the promotion on this kernel. Modes 3/4 (dual chain only): -10%."""
import os
HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, 'include/deep_gemm/impls/sm90_int8_gemm_1d2d.cuh')
DST = os.path.join(HERE, 'include/deep_gemm/impls/sm90_int8_gemm_1d2d_pp.cuh')
s = open(SRC).read()

def rep(old, new, n):
    global s
    c = s.count(old); assert c == n, (old[:100], c, n)
    s = s.replace(old, new)

# 1) header comment + kernel name + extra template parameter; helpers come from the default header (as in gen_kernel_db.py)
hdr_end = s.index('#pragma once')
s = ('// Math-warpgroup ping-pong (PP) variant of the INT8 port of DeepGEMM sm90_fp8_gemm_1d2d.cuh (MIT License, Copyright (c) 2025 DeepSeek).\n'
     '// Generated by kernels/deepgemm_int8/gen_kernel_pp.py from sm90_int8_gemm_1d2d.cuh -- do not edit by hand.\n'
     '// Same per-warpgroup mainloop as the default kernel (one int32 accumulator, wait<0> before every promotion), but the two math\n'
     '// warpgroups issue their WGMMA batches strictly alternately (named-barrier ordering), so one warpgroup promotes on the CUDA cores\n'
     '// while the other one owns the tensor cores. Same math, same k order -> bit-identical to the default kernel.\n') + s[hdr_end:]
rep('sm90_int8_gemm_1d2d_impl(float* sfb,', 'sm90_int8_gemm_1d2d_pp_impl(float* sfb,', 1)
rep('          typename epilogue_op_t>\nCUTLASS_GLOBAL', '          typename epilogue_op_t,\n          uint32_t kPPMode>\nCUTLASS_GLOBAL', 1)
i0 = s.index('template <uint32_t kNumFormerIters, uint32_t kGap, uint32_t kEnd, typename func_t>\nCUTLASS_DEVICE void dispatch_num_former_iters(')
i1 = s.index('template <cute::UMMA::Major kMajorSFB,')
assert i0 < i1
s = s[:i0] + ('// helpers (dispatch_num_former_iters, kPromoteMode / promote_i32, kOverlap) are shared with the default kernel\n'
              '\n') + s[i1:]
rep('#include <deep_gemm/scheduler/gemm.cuh>\n', '#include <deep_gemm/scheduler/gemm.cuh>\n#include <deep_gemm/impls/sm90_int8_gemm_1d2d.cuh>\n', 1)

# 2) drop the DG_INT8_OVERLAP experiment path, keep the default mainloop
start = '                  if constexpr (kOverlap and BLOCK_M / WAVE_BLOCK_M == 1 and BLOCK_M >= WGMMA::M) {'
end = '                  } else {\n                    #pragma unroll 8\n'
j0 = s.index(start); j1 = s.index(end); assert j0 < j1 and s.count(start) == 1 and s.count(end) == 1
s = s[:j0] + s[j1 + len('                  } else {\n'):]
rep('                        }\n                    }\n                  }\n                });\n            } else {',
    '                        }\n                    }\n                });\n            } else {', 1)

# 3) the ping-pong handshake, defined once per math warpgroup (before the persistent tile loop)
rep('        // Persistently schedule over blocks\n        while (scheduler.get_next_block(m_block_idx, n_block_idx)) {\n            // Decide the number of scales B to load',
    r'''        // (INT8 PP) math-warpgroup ping-pong: the two math warpgroups issue their WGMMA batches strictly alternately
        // (WG0 batch b, WG1 batch b, WG0 batch b+1, ...), so one warpgroup's promotion (I2F + FFMA on the CUDA cores) overlaps the
        // other warpgroup's batch on the tensor cores. Two named barriers (user ids 2/3 -> hw ids 10/11; the kernel already uses
        // hw ids 0, 8, 9): warpgroup w arrives on bar[w] after its commit, the other warpgroup syncs on bar[w] before its issue.
        //   kPPMode 1: WG0 syncs on bar[1] right after its own signal (uniform per batch, no tile-boundary bookkeeping)
        //   kPPMode 2: both sync before issuing; WG0 skips only the very first wait of the kernel, consumes WG1's last signal at the end
        // Both warpgroups run the same number of batches per tile (GemmType::Normal: is_computation_valid is always true).
        //   kPPMode 3: mode-1 handshake + two independent wgmma chains per warpgroup (k-steps 0,2 -> accum, 1,3 -> accum_b, exact
        //              int32 sum before the promotion): a single dependent 4-wgmma chain runs at ~57% of the tensor-core peak when a
        //              warpgroup is alone on the tensor cores, two interleaved chains keep the pipeline full (BLOCK_M = 128 only)
        //   kPPMode 4: the two chains WITHOUT the handshake (lockstep control experiment)
        //   kPPMode 5: TRUE tensor-core mutual exclusion: the signal is given after this warpgroup's wait<0> (its batch has finished),
        //              not after the issue -- with issue-order-only alternation (modes 1/2) the tensor cores arbitrate the two in-flight
        //              chains fairly, both batches finish together and both warpgroups still promote at the same time (measured:
        //              ~990 cycles per k-block, same as lockstep). Skip-first prologue / kernel-end consumption as in mode 2.
        //   kPPMode 6: mode 5 with the batch split in two commit groups (k-steps 0-2 | 3): signal after wait<1> (3/4 of the batch done)
        //              so the other warpgroup's wake-up + issue latency overlaps the last wgmma instead of idling the tensor cores.
        //   kPPMode 7: mode 5 (tensor-core mutual exclusion, signal after wait<0>) + the two chains of mode 3 (BLOCK_M = 128 only):
        //              a warpgroup alone on the tensor cores keeps them full with two interleaved chains, the other one promotes meanwhile
        constexpr bool kPPHandshake = (kPPMode == 1 or kPPMode == 2 or kPPMode == 3 or kPPMode == 5 or kPPMode == 6 or kPPMode == 7);
        constexpr bool kPPWG0WaitsAfter = (kPPMode == 1 or kPPMode == 3);
        constexpr bool kPPSignalAfterWait = (kPPMode == 5 or kPPMode == 6 or kPPMode == 7);
        constexpr bool kPPSplitGroup = (kPPMode == 6);
        constexpr bool kPPDualChain = (kPPMode == 3 or kPPMode == 4 or kPPMode == 7);
        constexpr uint32_t kPPBarBase = 2;
        const uint32_t pp_bar_mine = kPPBarBase + math_wg_idx, pp_bar_other = kPPBarBase + (math_wg_idx ^ 1);
        bool pp_first = true;
        auto pp_before_issue = [&]() {
            if constexpr (kNumMathThreads == 256 and kPPHandshake) {
                if constexpr (kPPWG0WaitsAfter) {
                    if (math_wg_idx == 1)
                        cutlass::arch::NamedBarrier::sync(kNumMathThreads, pp_bar_other);
                } else {
                    if (math_wg_idx == 1 or not pp_first)
                        cutlass::arch::NamedBarrier::sync(kNumMathThreads, pp_bar_other);
                    pp_first = false;
                }
            }
        };
        auto pp_after_issue = [&]() {
            if constexpr (kNumMathThreads == 256 and kPPHandshake and not kPPSignalAfterWait) {
                cutlass::arch::NamedBarrier::arrive(kNumMathThreads, pp_bar_mine);
                if constexpr (kPPWG0WaitsAfter) {
                    if (math_wg_idx == 0)
                        cutlass::arch::NamedBarrier::sync(kNumMathThreads, pp_bar_other);
                }
            }
        };
        auto pp_signal_done = [&]() {   // modes 5/6: my batch is (almost) retired -> the other warpgroup may take the tensor cores
            if constexpr (kNumMathThreads == 256 and kPPSignalAfterWait)
                cutlass::arch::NamedBarrier::arrive(kNumMathThreads, pp_bar_mine);
        };

        // Persistently schedule over blocks
        while (scheduler.get_next_block(m_block_idx, n_block_idx)) {
            // Decide the number of scales B to load''', 1)

# 4) handshake around every WGMMA batch of the default mainloop (per wave: 1 batch per k-block for BLOCK_M=128, 2 for BLOCK_M=256)
rep('                            // Commit WGMMA instructions\n                            #pragma unroll\n                            for (uint32_t i = 0; i < WGMMA::kNumAccum; ++ i)\n                                ptx::warpgroup_fence_operand(accum[i]);\n                            ptx::warpgroup_arrive();',
    '                            // (INT8 PP) wait for my turn on the tensor cores (all smem scale reads are above, as DeepGEMM requires)\n'
    '                            pp_before_issue();\n\n'
    '                            // Commit WGMMA instructions\n                            #pragma unroll\n                            for (uint32_t i = 0; i < WGMMA::kNumAccum; ++ i)\n                                ptx::warpgroup_fence_operand(accum[i]);\n                            ptx::warpgroup_arrive();', 1)
issue_old = '''                            // Commit WGMMA instructions
                            #pragma unroll
                            for (uint32_t i = 0; i < WGMMA::kNumAccum; ++ i)
                                ptx::warpgroup_fence_operand(accum[i]);
                            ptx::warpgroup_arrive();
                            #pragma unroll
                            for (uint32_t k = 0; k < BLOCK_K / WGMMA::K; ++ k) {
                                a_desc.reg32_[0] = a_desc_base_lo + (m_offset * BLOCK_K + k * WGMMA::K) / 16;
                                b_desc.reg32_[0] = b_desc_base_lo + k * WGMMA::K / 16;
                                WGMMA::wgmma(a_desc, b_desc, accum, k);
                            }
                            ptx::warpgroup_commit_batch();
                            #pragma unroll
                            for (uint32_t i = 0; i < WGMMA::kNumAccum; ++ i)
                                ptx::warpgroup_fence_operand(accum[i]);
                            ptx::warpgroup_wait<0>();
'''
issue_new = '''                            if constexpr (kPPDualChain) {
                                // (INT8 PP, dual chain) k-steps 0,2 -> accum, k-steps 1,3 -> accum_b: two independent wgmma chains keep the
                                // tensor-core pipeline full while this warpgroup is alone on it; exact int32 sum below (|partial| < 2^20)
                                #pragma unroll
                                for (uint32_t i = 0; i < WGMMA::kNumAccum; ++ i)
                                    ptx::warpgroup_fence_operand(accum[i]), ptx::warpgroup_fence_operand(accum_b[i]);
                                ptx::warpgroup_arrive();
                                #pragma unroll
                                for (uint32_t k = 0; k < BLOCK_K / WGMMA::K; ++ k) {
                                    a_desc.reg32_[0] = a_desc_base_lo + (m_offset * BLOCK_K + k * WGMMA::K) / 16;
                                    b_desc.reg32_[0] = b_desc_base_lo + k * WGMMA::K / 16;
                                    WGMMA::wgmma(a_desc, b_desc, (k & 1) ? accum_b : accum, k >> 1);   // k < 2: scale-d = 0 zeroes the chain
                                }
                                ptx::warpgroup_commit_batch();
                                // (INT8 PP) hand the tensor cores to the other warpgroup, then retire my own batch and promote it
                                pp_after_issue();
                                #pragma unroll
                                for (uint32_t i = 0; i < WGMMA::kNumAccum; ++ i)
                                    ptx::warpgroup_fence_operand(accum[i]), ptx::warpgroup_fence_operand(accum_b[i]);
                                ptx::warpgroup_wait<0>();
                                pp_signal_done();   // (INT8 PP, mode 7) my batch has left the tensor cores
                                #pragma unroll
                                for (uint32_t i = 0; i < WGMMA::kNumAccum; ++ i)
                                    accum[i] += accum_b[i];   // exact: the same int32 dot product as the single chain
                            } else {
                            // Commit WGMMA instructions
                            #pragma unroll
                            for (uint32_t i = 0; i < WGMMA::kNumAccum; ++ i)
                                ptx::warpgroup_fence_operand(accum[i]);
                            ptx::warpgroup_arrive();
                            #pragma unroll
                            for (uint32_t k = 0; k < BLOCK_K / WGMMA::K; ++ k) {
                                if constexpr (kPPSplitGroup) {
                                    if (k == BLOCK_K / WGMMA::K - 1)
                                        ptx::warpgroup_commit_batch();   // (INT8 PP, mode 6) group 1 = k-steps 0..2, group 2 = the last k-step
                                }
                                a_desc.reg32_[0] = a_desc_base_lo + (m_offset * BLOCK_K + k * WGMMA::K) / 16;
                                b_desc.reg32_[0] = b_desc_base_lo + k * WGMMA::K / 16;
                                WGMMA::wgmma(a_desc, b_desc, accum, k);
                            }
                            ptx::warpgroup_commit_batch();
                            // (INT8 PP, modes 1-3) hand the tensor cores to the other warpgroup right after the issue
                            pp_after_issue();
                            #pragma unroll
                            for (uint32_t i = 0; i < WGMMA::kNumAccum; ++ i)
                                ptx::warpgroup_fence_operand(accum[i]);
                            if constexpr (kPPSplitGroup) {
                                ptx::warpgroup_wait<1>();   // k-steps 0..2 retired (no accumulator read before wait<0> below)
                                pp_signal_done();
                            }
                            ptx::warpgroup_wait<0>();
                            if constexpr (kPPSignalAfterWait and not kPPSplitGroup)
                                pp_signal_done();   // (INT8 PP, mode 5) my batch has left the tensor cores
                            }
'''
rep(issue_old, issue_new, 1)
# second int32 accumulator for the dual-chain modes (unused -> removed by the compiler otherwise)
rep('            int32_t accum[WGMMA::kNumAccum];\n',
    '            int32_t accum[WGMMA::kNumAccum];\n'
    '            int32_t accum_b[WGMMA::kNumAccum];   // (INT8 PP) second chain of kPPMode >= 3 (BLOCK_M = 128: 128 + 64 live registers, as the DB kernel)\n'
    '            DG_STATIC_ASSERT(not kPPDualChain or BLOCK_M / WAVE_BLOCK_M == 1, "dual-chain ping-pong needs one 64-row wave per warpgroup (BLOCK_M = 128)");\n', 1)

# 5) mode 2: balance the named-barrier state at kernel exit (WG1's last signal has no matching wait otherwise)
rep('            __syncwarp();\n        }\n    }\n#else',
    '            __syncwarp();\n        }\n'
    '        // (INT8 PP, modes 2/5/6) consume WG1\'s last signal so the kernel exits with balanced named-barrier state\n'
    '        if constexpr (kNumMathThreads == 256 and (kPPMode == 2 or kPPMode == 5 or kPPMode == 6 or kPPMode == 7)) {\n'
    '            if (math_wg_idx == 0 and not pp_first)\n'
    '                cutlass::arch::NamedBarrier::sync(kNumMathThreads, pp_bar_other);\n'
    '        }\n'
    '    }\n#else', 1)
open(DST, 'w').write(s)
print('wrote', DST)

# 6) launcher_pp.cuh: launcher.cuh with the PP kernel and the extra kPPMode template parameter
L = open(os.path.join(HERE, 'launcher.cuh')).read()
def lrep(old, new, n):
    global L
    c = L.count(old); assert c == n, (old[:80], c, n)
    L = L.replace(old, new)
lrep('#pragma once\n#include <cuda.h>', '#pragma once\n#include "launcher.cuh"\n#include <cuda.h>', 1)
lrep('#include <deep_gemm/impls/sm90_int8_gemm_1d2d.cuh>\n', '#include <deep_gemm/impls/sm90_int8_gemm_1d2d_pp.cuh>\n', 1)
lrep('          uint32_t kNumTMAMulticast, bool kIsTMAMulticastOnA>\nvoid launch(const Args& args) {',
     '          uint32_t kNumTMAMulticast, bool kIsTMAMulticastOnA, uint32_t kPPMode>\nvoid launch_pp(const Args& args) {', 1)
lrep('auto kernel = &deep_gemm::sm90_int8_gemm_1d2d_impl<', 'auto kernel = &deep_gemm::sm90_int8_gemm_1d2d_pp_impl<', 1)
lrep('        cutlass::bfloat16_t, deep_gemm::epilogue::transform::EpilogueIdentity>;',
     '        cutlass::bfloat16_t, deep_gemm::epilogue::transform::EpilogueIdentity, kPPMode>;', 1)
k0 = L.index('#define DGINT8_CUDA_CHECK'); k1 = L.index('template <uint32_t SHAPE_N, uint32_t SHAPE_K, uint32_t BLOCK_M')
L = L[:k0] + '// helpers (make_tma_2d, smem_size_for, ...) come from launcher.cuh\n\n' + L[k1:]
L = ('// Host launcher for the PP (math-warpgroup ping-pong) variant: launcher.cuh with kernel sm90_int8_gemm_1d2d_pp_impl<..., kPPMode>.\n'
     '// Generated by gen_kernel_pp.py -- do not edit by hand.\n') + L[L.index('#pragma once'):]
open(os.path.join(HERE, 'launcher_pp.cuh'), 'w').write(L)
print('wrote launcher_pp.cuh')
