"""Generate include/deep_gemm/impls/sm90_int8_gemm_1d2d_wi.cuh: the "wave interleave" experiment on top of the generated INT8
kernel (sm90_int8_gemm_1d2d.cuh). New kernel name `sm90_int8_gemm_1d2d_wi_impl` + one extra template parameter `kWaveMode`;
the default kernel / cfg ids 0-18 are untouched (this file is only included by launcher_wi.cuh = new cfg ids).

  kWaveMode 1: literal two-wave interleave for BLOCK_M == 256: each 64x128 wave is its own commit group, promotion of wave w
               runs while the other wave's WGMMAs are in flight. Needs 2 x 64 live int32 accumulators + 128 fp32 finals
               = 256 live registers > the 232-register math budget -> ptxas spills (kept for the evidence).
  kWaveMode 2: quarter-wave interleave: each 64-row wave is split into two 64x(BLOCK_N/2) commit groups (m64n64k32 WGMMA);
               two rotating int32 buffers of 32 registers (same 64 int32 budget as the default kernel). At every promotion
               exactly one group (128 tensor-core cycles) is in flight. Bit-identical: the int32 sums over a 128-K block are
               exact and every final element receives the same fp32 FFMA sequence (final += ps * float(acc)) in the same k order.
Every edit is a checked string replacement of the generated base header so the diff stays auditable. Re-run after editing."""
import os
HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, 'include/deep_gemm/impls/sm90_int8_gemm_1d2d.cuh')
DST = os.path.join(HERE, 'include/deep_gemm/impls/sm90_int8_gemm_1d2d_wi.cuh')
s = open(SRC).read()

def rep(old, new, n=1):
    global s
    c = s.count(old); assert c == n, (old[:80], c, n)
    s = s.replace(old, new)

# 1) header comment, drop the helper definitions (provided by the base header, which we include)
hdr_end = s.index('#pragma once')
s = ('// Wave-interleave experiment on the INT8 port of DeepGEMM sm90_fp8_gemm_1d2d.cuh (MIT License, Copyright (c) 2025 DeepSeek).\n'
     '// Generated by kernels/deepgemm_int8/gen_kernel_wi.py from sm90_int8_gemm_1d2d.cuh -- do not edit by hand.\n'
     '// Adds template parameter kWaveMode (1: two-wave interleave, 2: quarter-wave n64 interleave); see gen_kernel_wi.py.\n') + s[hdr_end:]
start = s.index('template <uint32_t kNumFormerIters, uint32_t kGap, uint32_t kEnd, typename func_t>')
end = s.index('template <cute::UMMA::Major kMajorSFB,')
s = s[:start] + s[end:]
rep('#include <deep_gemm/scheduler/gemm.cuh>\n',
    '#include <deep_gemm/scheduler/gemm.cuh>\n#include <deep_gemm/impls/sm90_int8_gemm_1d2d.cuh>   // base kernel: dispatch_num_former_iters, promote_i32, kPromoteMode\n')

# 2) kernel name + template parameter
rep('          typename epilogue_op_t>\nCUTLASS_GLOBAL', '          typename epilogue_op_t,\n          uint32_t kWaveMode>\nCUTLASS_GLOBAL')
rep('sm90_int8_gemm_1d2d_impl(', 'sm90_int8_gemm_1d2d_wi_impl(')
rep('#include <deep_gemm/impls/sm90_int8_gemm_1d2d.cuh>   // base kernel: dispatch_num_former_iters, promote_i32, kPromoteMode\n',
    '#include <deep_gemm/impls/sm90_int8_gemm_1d2d.cuh>   // base kernel: dispatch_num_former_iters, promote_i32, kPromoteMode\n'
    '#ifndef DG_WI_PRED_ARRIVE\n#define DG_WI_PRED_ARRIVE 0   // 1: branch-free (compile-tested only; does not remove C7514) (@p predicated) empty-barrier arrive while a WGMMA group is in flight\n#endif\n'
    '#ifndef DG_WI_DIAG\n#define DG_WI_DIAG 0   // compile-only diagnostics (WRONG results): 1 = no stage release, 2 = no full-barrier wait\n#endif\n')

# 3) the interleaved mainloops, inserted in front of the existing (unchanged) paths
old = """                dispatch_num_former_iters<0, kGap, kEnd>(kShouldOptimize ? num_former_iters : 0, [&](auto _) {
                  if constexpr (kOverlap and BLOCK_M / WAVE_BLOCK_M == 1 and BLOCK_M >= WGMMA::M) {"""
new = r"""                dispatch_num_former_iters<0, kGap, kEnd>(kShouldOptimize ? num_former_iters : 0, [&](auto _) {
                  if constexpr (kWaveMode != 0) {
                    // (INT8 port, wave interleave) each math warpgroup owns 2 waves of 64 rows (BLOCK_M == 256); one B scale per k-block
                    DG_STATIC_ASSERT(BLOCK_M / WAVE_BLOCK_M == 2 and BLOCK_M >= WGMMA::M and kMustUseUniformedScaleB,
                                     "wave interleave needs BLOCK_M == 256 and BLOCK_N | 128");
                    DG_STATIC_ASSERT(kWaveMode == 1 or kWaveMode == 2, "kWaveMode in {1, 2}");
                    constexpr uint32_t kGroupN = kWaveMode == 1 ? BLOCK_N : BLOCK_N / 2;     // columns per commit group
                    using WGMMA_G = typename mma::sm90::S8MMASelector<kGroupN>::type;
                    constexpr uint32_t kNumAccumG = WGMMA_G::kNumAccum;
                    DG_STATIC_ASSERT(kNumAccumG % 4 == 0 and WGMMA_G::K == WGMMA::K, "bad group shape");
                    // Two rotating int32 accumulator buffers (distinct arrays so the fences pin exactly one of them)
                    int32_t acc_x[kNumAccumG], acc_y[kNumAccumG];
                    float ps_cur[4], ps_prev[4];   // (wave, row) scale products of the current / previous k-block
                    uint32_t prev_stage_idx = 0;
                    auto fence = [&](int32_t* acc) {
                        if constexpr (DG_WI_DIAG == 5) return;
                        #pragma unroll
                        for (uint32_t i = 0; i < kNumAccumG; ++ i)
                            ptx::warpgroup_fence_operand(acc[i]);
                    };
                    auto wait_prev = [&]() {   // retire the older of the two in-flight groups (DIAG 3: full drain = no overlap, control)
                        if constexpr (DG_WI_DIAG == 3) ptx::warpgroup_wait<0>(); else ptx::warpgroup_wait<1>();
                    };
                    // Issue one commit group: 64 rows (wave) x kGroupN columns (half) of the current stage
                    auto issue = [&](int32_t* acc, const uint32_t& wave, const uint32_t& half) {
                        const auto m_offset = wave * WAVE_BLOCK_M;
                        const auto a_desc_base_lo = a_desc_lo + stage_idx * (SMEM_A_SIZE_PER_STAGE / 16);
                        const auto b_desc_base_lo = b_desc_lo + stage_idx * (SMEM_B_SIZE_PER_STAGE / 16) + (half * kGroupN * BLOCK_K) / 16;
                        fence(acc);
                        ptx::warpgroup_arrive();
                        #pragma unroll
                        for (uint32_t k = 0; k < BLOCK_K / WGMMA_G::K; ++ k) {
                            a_desc.reg32_[0] = a_desc_base_lo + (m_offset * BLOCK_K + k * WGMMA_G::K) / 16;
                            b_desc.reg32_[0] = b_desc_base_lo + k * WGMMA_G::K / 16;
                            WGMMA_G::wgmma(a_desc, b_desc, acc, k);
                        }
                        ptx::warpgroup_commit_batch();
                        if constexpr (DG_WI_DIAG != 4) fence(acc);
                    };
                    // Promote one retired group into its slice of `final_accum` (same per-element FFMA order as the default path:
                    // column chunk i of half h is chunk h * kNumAccumG / 4 + i of the 64xBLOCK_N wave)
                    auto promote = [&](const int32_t* acc, const uint32_t& wave, const uint32_t& half, const float* ps) {
                        const float s_0 = ps[wave * 2 + 0], s_1 = ps[wave * 2 + 1];
                        auto shifted_accum = final_accum + WGMMA::kNumAccum * wave + kNumAccumG * half;
                        #pragma unroll
                        for (uint32_t i = 0; i < kNumAccumG / 4; ++ i) {
                            shifted_accum[i * 4 + 0] += s_0 * promote_i32<kPromoteMode>(acc[i * 4 + 0]);
                            shifted_accum[i * 4 + 1] += s_0 * promote_i32<kPromoteMode>(acc[i * 4 + 1]);
                            shifted_accum[i * 4 + 2] += s_1 * promote_i32<kPromoteMode>(acc[i * 4 + 2]);
                            shifted_accum[i * 4 + 3] += s_1 * promote_i32<kPromoteMode>(acc[i * 4 + 3]);
                        }
                    };
                    // All shared-memory reads of a k-block's scales precede its first `warpgroup_arrive` (waits for the stage's TMA)
                    auto load_scales = [&](const uint32_t& k_block_idx, float* ps) {
                        const float scale_b = ptx::ld_shared(smem_sfb + k_block_idx);
                        if constexpr (DG_WI_DIAG != 2)
                            full_barriers[stage_idx]->wait(phase);
                        #pragma unroll
                        for (uint32_t w = 0; w < 2; ++ w) {
                            const float scale_a_0 = ptx::ld_shared(smem_sfa[stage_idx] + r_0 + w * WAVE_BLOCK_M);
                            const float scale_a_1 = ptx::ld_shared(smem_sfa[stage_idx] + r_1 + w * WAVE_BLOCK_M);
                            ps[w * 2 + 0] = scale_a_0 * scale_b, ps[w * 2 + 1] = scale_a_1 * scale_b;
                        }
                    };
                    // Stage release while another group is in flight: DeepGEMM's `lane_idx < N ? arrive() : void()` is a branch; the
                    // predicated form keeps the mainloop a single basic block for ptxas' wgmma pipeline analysis
                    auto release_stage = [&](const uint32_t& s) {
                        if constexpr (DG_WI_DIAG == 1) {
                            return;
                        } else if constexpr (DG_WI_PRED_ARRIVE != 0) {
                            const uint32_t pred = kNumTMAMulticast == 1 ? (lane_idx == 0) : (lane_idx < kNumTMAMulticast);
                            const uint32_t target_cta = (kNumTMAMulticast == 1 or not scheduler.is_peer_cta_alive) ? cute::block_rank_in_cluster() : lane_idx;
                            const uint32_t addr = cute::cast_smem_ptr_to_uint(empty_barriers[s]);
                            asm volatile("{\n\t.reg .pred p;\n\t.reg .b32 remAddr32;\n\tsetp.ne.b32 p, %2, 0;\n\t"
                                         "@p mapa.shared::cluster.u32 remAddr32, %0, %1;\n\t@p mbarrier.arrive.shared::cluster.b64 _, [remAddr32];\n\t}"
                                         :: "r"(addr), "r"(target_cta), "r"(pred) : "memory");
                        } else {
                            empty_barrier_arrive_at(s);
                        }
                    };
                    auto rotate_scales = [&]() {
                        #pragma unroll
                        for (uint32_t i = 0; i < 4; ++ i)
                            ps_prev[i] = ps_cur[i];
                        prev_stage_idx = stage_idx;
                    };
                    uint32_t k_block_idx = 0;
                    if constexpr (kWaveMode == 2) {
                        // groups per k-block: q0 = (wave 0, half 0) -> X, q1 = (0, 1) -> Y, q2 = (1, 0) -> X, q3 = (1, 1) -> Y.
                        // Invariant at each promotion: exactly one group is in flight, the promoted buffer's group is retired.
                        load_scales(k_block_idx, ps_cur);
                        issue(acc_x, 0, 0);
                        issue(acc_y, 0, 1); wait_prev(); fence(acc_x); promote(acc_x, 0, 0, ps_cur);
                        issue(acc_x, 1, 0); wait_prev(); fence(acc_y); promote(acc_y, 0, 1, ps_cur);
                        issue(acc_y, 1, 1); wait_prev(); fence(acc_x); promote(acc_x, 1, 0, ps_cur);
                        rotate_scales(); advance_pipeline(k_block_idx);
                        #pragma unroll 1
                        while (k_block_idx < num_total_k_blocks) {
                            load_scales(k_block_idx, ps_cur);
                            // q3 of the previous k-block retires here -> its stage is fully consumed -> release it
                            issue(acc_x, 0, 0); wait_prev(); fence(acc_y); release_stage(prev_stage_idx); promote(acc_y, 1, 1, ps_prev);
                            issue(acc_y, 0, 1); wait_prev(); fence(acc_x); promote(acc_x, 0, 0, ps_cur);
                            issue(acc_x, 1, 0); wait_prev(); fence(acc_y); promote(acc_y, 0, 1, ps_cur);
                            issue(acc_y, 1, 1); wait_prev(); fence(acc_x); promote(acc_x, 1, 0, ps_cur);
                            rotate_scales(); advance_pipeline(k_block_idx);
                        }
                        ptx::warpgroup_wait<0>(); fence(acc_y); release_stage(prev_stage_idx); promote(acc_y, 1, 1, ps_prev);
                    } else {
                        // literal two-wave interleave: wave 0 -> X, wave 1 -> Y (one 64xBLOCK_N commit group each)
                        load_scales(k_block_idx, ps_cur);
                        issue(acc_x, 0, 0);
                        issue(acc_y, 1, 0); wait_prev(); fence(acc_x); promote(acc_x, 0, 0, ps_cur);
                        rotate_scales(); advance_pipeline(k_block_idx);
                        #pragma unroll 1
                        while (k_block_idx < num_total_k_blocks) {
                            load_scales(k_block_idx, ps_cur);
                            issue(acc_x, 0, 0); wait_prev(); fence(acc_y); release_stage(prev_stage_idx); promote(acc_y, 1, 0, ps_prev);
                            issue(acc_y, 1, 0); wait_prev(); fence(acc_x); promote(acc_x, 0, 0, ps_cur);
                            rotate_scales(); advance_pipeline(k_block_idx);
                        }
                        ptx::warpgroup_wait<0>(); fence(acc_y); release_stage(prev_stage_idx); promote(acc_y, 1, 0, ps_prev);
                    }
                  } else if constexpr (kOverlap and BLOCK_M / WAVE_BLOCK_M == 1 and BLOCK_M >= WGMMA::M) {"""
rep(old, new)
open(DST, 'w').write(s)
print('wrote', DST)
