"""Generate the double-buffered-accumulator ("DB") variant of the INT8 1D2D kernel:
  include/deep_gemm/impls/sm90_int8_gemm_1d2d_db.cuh  (kernel `sm90_int8_gemm_1d2d_db_impl`, derived from the generated
                                                        sm90_int8_gemm_1d2d.cuh by checked string edits)
  launcher_db.cuh                                      (`dgint8::launch_db<...>`, derived from launcher.cuh)
Only the BLOCK_M in {64, 128} mainloop differs (one 64-row wave per math warpgroup): two distinct named int32 accumulator arrays
acc0/acc1, WGMMA(k+1) is issued into one buffer, `wgmma.wait_group 1` retires k, the retired buffer is fenced
(warpgroup_fence_operand) right after that wait, its smem stage is released and it is promoted while k+1's WGMMAs run.
Per-element math and k order are unchanged: final += (sa*sb) * float(acc) in fp32, k ascending -> bit-identical to the default kernel.

Why the old DG_INT8_OVERLAP path was slower (ptxas C7514, all waits lowered to DEPBAR.LE gsb0, 0x0): ptxas only certifies the
`wait_group 1` pattern when every wgmma group is issued AND retired inside one straight-line region -- a group in flight across the
k-loop back-edge (old path, and also `--mode pair`, the CUTLASS DB=1 loop shape) is rejected and the whole pipeline is serialized
(SASS: one WARPGROUP.ARRIVE per IGMMA, promotion I2F/FFMA moved between the IGMMAs). `--mode region` (default) therefore processes
kU (= --unroll, default 8) k-blocks per straight-line region with a full drain (wait<0>) at the region end: 7 of 8 promotions are
hidden, ptxas emits 7x `DEPBAR.LE gsb0, 0x1` + 1x `0x0` per region, 0 spills for the shape-compiled 128x128 configs, no C7514.
The default kernel / launcher / configs 0-18 are untouched. Re-run after editing this file (after gen_kernel.py)."""
import os
HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, 'include/deep_gemm/impls/sm90_int8_gemm_1d2d.cuh')
DST = os.path.join(HERE, 'include/deep_gemm/impls/sm90_int8_gemm_1d2d_db.cuh')
s = open(SRC).read()

def rep(old, new, n):
    global s
    c = s.count(old); assert c == n, (old[:80], c, n)
    s = s.replace(old, new)

# 1) header comment + kernel name; helpers (dispatch_num_former_iters, kPromoteMode, promote_i32, kOverlap) come from the default header
hdr_end = s.index('#pragma once')
s = ('// Double-buffered-accumulator (DB) variant of the INT8 port of DeepGEMM sm90_fp8_gemm_1d2d.cuh (MIT License, Copyright (c) 2025 DeepSeek).\n'
     '// Generated by kernels/deepgemm_int8/gen_kernel_db.py from sm90_int8_gemm_1d2d.cuh -- do not edit by hand.\n'
     '// Mainloop for BLOCK_M in {64, 128}: WGMMA(k+1) into acc1 while promote(k) reads acc0 (and vice versa); same math, same k order.\n') + s[hdr_end:]
rep('sm90_int8_gemm_1d2d_impl(float* sfb,', 'sm90_int8_gemm_1d2d_db_impl(float* sfb,', 1)
i0 = s.index('template <uint32_t kNumFormerIters, uint32_t kGap, uint32_t kEnd, typename func_t>\nCUTLASS_DEVICE void dispatch_num_former_iters(')
i1 = s.index('template <cute::UMMA::Major kMajorSFB,')
assert i0 < i1
s = s[:i0] + ('// helpers (dispatch_num_former_iters, kPromoteMode / promote_i32, kOverlap) are shared with the default kernel\n'
              '\n') + s[i1:]
rep('#include <deep_gemm/scheduler/gemm.cuh>\n', '#include <deep_gemm/scheduler/gemm.cuh>\n#include <deep_gemm/impls/sm90_int8_gemm_1d2d.cuh>\n', 1)

# 2) replace the DG_INT8_OVERLAP mainloop by the DB mainloop (the BLOCK_M == 256 two-wave path keeps the default loop)
start = '                  if constexpr (kOverlap and BLOCK_M / WAVE_BLOCK_M == 1 and BLOCK_M >= WGMMA::M) {'
end = '                  } else {\n                    #pragma unroll 8\n'
j0 = s.index(start); j1 = s.index(end); assert j0 < j1 and s.count(start) == 1 and s.count(end) == 1
db = r'''                  if constexpr (BLOCK_M / WAVE_BLOCK_M == 1 and BLOCK_M >= WGMMA::M) {
                    // (INT8 DB) double-buffered int32 accumulators: the WGMMAs of k-block k+1 execute while k-block k is promoted on
                    // the CUDA cores. Two distinct named arrays, compile-time buffer selection (hand-unrolled even/odd loop), and the
                    // buffer about to be read is fenced right after the `wgmma.wait_group 1` that retires its group.
                    int32_t acc0[WGMMA::kNumAccum], acc1[WGMMA::kNumAccum];
                    float sc0[4], sc1[4];   // {scale_0_0, scale_1_0, scale_0_1, scale_1_1} of the k-block held in acc0 / acc1
                    auto fence_all = [&](int32_t* acc) {
                        #pragma unroll
                        for (uint32_t i = 0; i < WGMMA::kNumAccum; ++ i)
                            ptx::warpgroup_fence_operand(acc[i]);
                    };
                    // Wait for this stage's TMA and read the k-block's scales (all smem reads before `warpgroup_arrive`)
                    auto load_scales = [&](const uint32_t& k_block_idx, float* sc) {
                        const float scale_b_0 = ptx::ld_shared(smem_sfb + k_block_idx);
                        float scale_b_1 = 0;
                        if constexpr (not kMustUseUniformedScaleB)
                            scale_b_1 = ptx::ld_shared(smem_sfb + k_block_idx + shape_k_scales);
                        full_barriers[stage_idx]->wait(phase);
                        const float scale_a_0 = ptx::ld_shared(smem_sfa[stage_idx] + r_0);
                        const float scale_a_1 = ptx::ld_shared(smem_sfa[stage_idx] + r_1);
                        sc[0] = scale_a_0 * scale_b_0, sc[1] = scale_a_1 * scale_b_0;
                        if constexpr (not kMustUseUniformedScaleB)
                            sc[2] = scale_a_0 * scale_b_1, sc[3] = scale_a_1 * scale_b_1;
                    };
                    auto issue = [&](int32_t* acc) {
                        const auto a_desc_base_lo = a_desc_lo + stage_idx * (SMEM_A_SIZE_PER_STAGE / 16);
                        const auto b_desc_base_lo = b_desc_lo + stage_idx * (SMEM_B_SIZE_PER_STAGE / 16);
                        fence_all(acc);
                        ptx::warpgroup_arrive();
                        #pragma unroll
                        for (uint32_t k = 0; k < BLOCK_K / WGMMA::K; ++ k) {
                            a_desc.reg32_[0] = a_desc_base_lo + (k * WGMMA::K) / 16;
                            b_desc.reg32_[0] = b_desc_base_lo + k * WGMMA::K / 16;
                            WGMMA::wgmma(a_desc, b_desc, acc, k);   // k == 0: scale-d = 0 zeroes the buffer
                        }
                        ptx::warpgroup_commit_batch();
                        fence_all(acc);
                    };
                    // Same per-element expression and k order as the default mainloop: final += (sa * sb) * float(acc), fp32
                    auto promote = [&](const int32_t* acc, const float* sc) {
                        #pragma unroll
                        for (uint32_t i = 0; i < WGMMA::kNumAccum / 4; ++ i) {
                            const bool predicate = kMustUseUniformedScaleB or i < num_former_iters;
                            final_accum[i * 4 + 0] += (predicate ? sc[0] : sc[2]) * promote_i32<kPromoteMode>(acc[i * 4 + 0]);
                            final_accum[i * 4 + 1] += (predicate ? sc[0] : sc[2]) * promote_i32<kPromoteMode>(acc[i * 4 + 1]);
                            final_accum[i * 4 + 2] += (predicate ? sc[1] : sc[3]) * promote_i32<kPromoteMode>(acc[i * 4 + 2]);
                            final_accum[i * 4 + 3] += (predicate ? sc[1] : sc[3]) * promote_i32<kPromoteMode>(acc[i * 4 + 3]);
                        }
                    };
                    // Retire the older in-flight group (buffer `acc`), release its smem stage, promote it while the newer group runs
                    auto retire_and_promote = [&](int32_t* acc, const float* sc, const uint32_t& s) {
                        ptx::warpgroup_wait<1>();
                        fence_all(acc);   // reads of `acc` below must stay below the wait (this is what the old overlap path lacked)
                        empty_barrier_arrive_at(s);
                        promote(acc, sc);
                    };
LOOP_BODY
'''
loop_pair = r'''                    uint32_t k_block_idx = 0, prev_stage_idx;
                    // Prologue: k-block 0 -> acc0
                    load_scales(k_block_idx, sc0);
                    issue(acc0);
                    prev_stage_idx = stage_idx;
                    advance_pipeline(k_block_idx);
                    // Pairs (single-exit loop, CUTLASS DB=1 shape): k -> acc1 while acc0 (k-1) is promoted, k+1 -> acc0 while acc1 (k) is promoted
                    #pragma unroll 1
                    for (; k_block_idx + 1 < num_total_k_blocks; ) {
                        load_scales(k_block_idx, sc1);
                        issue(acc1);
                        retire_and_promote(acc0, sc0, prev_stage_idx);
                        prev_stage_idx = stage_idx;
                        advance_pipeline(k_block_idx);
                        load_scales(k_block_idx, sc0);
                        issue(acc0);
                        retire_and_promote(acc1, sc1, prev_stage_idx);
                        prev_stage_idx = stage_idx;
                        advance_pipeline(k_block_idx);
                    }
                    // Tail: one more k-block (odd count) or none; then drain
                    if (k_block_idx < num_total_k_blocks) {
                        load_scales(k_block_idx, sc1);
                        issue(acc1);
                        retire_and_promote(acc0, sc0, prev_stage_idx);
                        prev_stage_idx = stage_idx;
                        advance_pipeline(k_block_idx);
                        ptx::warpgroup_wait<0>();
                        fence_all(acc1);
                        empty_barrier_arrive_at(prev_stage_idx);
                        promote(acc1, sc1);
                    } else {
                        ptx::warpgroup_wait<0>();
                        fence_all(acc0);
                        empty_barrier_arrive_at(prev_stage_idx);
                        promote(acc0, sc0);
                    }
'''
loop_region = r'''                    // Straight-line regions of kU k-blocks: buffers alternate inside the region, every group is retired (wait<0>) at the
                    // region end, so no wgmma group is in flight across a loop back-edge; 1 of kU promotions per region is exposed.
                    constexpr uint32_t kU = UNROLL_LITERAL;
                    uint32_t k_block_idx = 0, prev_stage_idx = 0;
                    #pragma unroll 1
                    while (k_block_idx + kU <= num_total_k_blocks) {
                        load_scales(k_block_idx, sc0);
                        issue(acc0);
                        prev_stage_idx = stage_idx;
                        advance_pipeline(k_block_idx);
                        #pragma unroll
                        for (uint32_t j = 1; j < kU; ++ j) {
                            int32_t* cur = (j & 1) ? acc1 : acc0; int32_t* prev = (j & 1) ? acc0 : acc1;
                            float* sc_cur = (j & 1) ? sc1 : sc0; float* sc_prev = (j & 1) ? sc0 : sc1;
                            load_scales(k_block_idx, sc_cur);
                            issue(cur);
                            retire_and_promote(prev, sc_prev, prev_stage_idx);
                            prev_stage_idx = stage_idx;
                            advance_pipeline(k_block_idx);
                        }
                        {
                            int32_t* last = ((kU - 1) & 1) ? acc1 : acc0; float* sc_last = ((kU - 1) & 1) ? sc1 : sc0;
                            ptx::warpgroup_wait<0>();
                            fence_all(last);
                            empty_barrier_arrive_at(prev_stage_idx);
                            promote(last, sc_last);
                        }
                    }
                    // Remainder (< kU k-blocks): not overlapped, same math
                    #pragma unroll 1
                    while (k_block_idx < num_total_k_blocks) {
                        load_scales(k_block_idx, sc0);
                        issue(acc0);
                        ptx::warpgroup_wait<0>();
                        fence_all(acc0);
                        empty_barrier_arrive();
                        promote(acc0, sc0);
                        advance_pipeline(k_block_idx);
                    }
'''
import sys
MODE = sys.argv[sys.argv.index('--mode') + 1] if '--mode' in sys.argv else 'region'   # 'region' (default, ptxas-certified) or 'pair' (CUTLASS DB=1 shape; still C7514 here)
assert MODE in ('pair', 'region')
db = db.replace('LOOP_BODY\n', loop_pair if MODE == 'pair' else loop_region)
UNROLL = sys.argv[sys.argv.index('--unroll') + 1] if '--unroll' in sys.argv else '8'   # kU: k-blocks per straight-line region (nvcc does not macro-expand #pragma unroll)
db = db.replace('UNROLL_LITERAL', UNROLL)
s = s[:j0] + db + s[j1:]
open(DST, 'w').write(s)
print('wrote', DST)

# 3) launcher_db.cuh: launcher.cuh with the DB kernel
L = open(os.path.join(HERE, 'launcher.cuh')).read()
def lrep(old, new, n):
    global L
    c = L.count(old); assert c == n, (old[:80], c, n)
    L = L.replace(old, new)
lrep('#pragma once\n#include <cuda.h>', '#pragma once\n#include "launcher.cuh"\n#include <cuda.h>', 1)
lrep('#include <deep_gemm/impls/sm90_int8_gemm_1d2d.cuh>\n', '#include <deep_gemm/impls/sm90_int8_gemm_1d2d_db.cuh>\n', 1)
lrep('void launch(const Args& args) {', 'void launch_db(const Args& args) {', 1)
lrep('auto kernel = &deep_gemm::sm90_int8_gemm_1d2d_impl<', 'auto kernel = &deep_gemm::sm90_int8_gemm_1d2d_db_impl<', 1)
# drop the helper definitions (already defined by launcher.cuh); keep only launch_db
k0 = L.index('#define DGINT8_CUDA_CHECK'); k1 = L.index('template <uint32_t SHAPE_N, uint32_t SHAPE_K, uint32_t BLOCK_M')
L = L[:k0] + '// helpers (make_tma_2d, smem_size_for, ...) come from launcher.cuh\n\n' + L[k1:]
L = ('// Host launcher for the DB (double-buffered accumulator) variant: launcher.cuh with kernel sm90_int8_gemm_1d2d_db_impl.\n'
     '// Generated by gen_kernel_db.py -- do not edit by hand.\n') + L[L.index('#pragma once'):]
open(os.path.join(HERE, 'launcher_db.cuh'), 'w').write(L)
print('wrote launcher_db.cuh')
