// generated by occ/gen_occ.py
#pragma once
#include "../dgint8_args.h"
#include "occ_report.h"
struct DgInt8OccCfg { int block_m, block_n, stages, mcast, on_a, shape_n, shape_k, math_threads, min_blocks, math_regs, is_db, smem; const char* name; };
void dgint8_occ_run_0(const dgint8::Args& args, dgint8::OccReport* rep);
void dgint8_occ_run_1(const dgint8::Args& args, dgint8::OccReport* rep);
void dgint8_occ_run_2(const dgint8::Args& args, dgint8::OccReport* rep);
void dgint8_occ_run_3(const dgint8::Args& args, dgint8::OccReport* rep);
void dgint8_occ_run_4(const dgint8::Args& args, dgint8::OccReport* rep);
void dgint8_occ_run_5(const dgint8::Args& args, dgint8::OccReport* rep);
void dgint8_occ_run_6(const dgint8::Args& args, dgint8::OccReport* rep);
void dgint8_occ_run_7(const dgint8::Args& args, dgint8::OccReport* rep);
void dgint8_occ_run_8(const dgint8::Args& args, dgint8::OccReport* rep);
void dgint8_occ_run_9(const dgint8::Args& args, dgint8::OccReport* rep);
void dgint8_occ_run_10(const dgint8::Args& args, dgint8::OccReport* rep);
void dgint8_occ_run_11(const dgint8::Args& args, dgint8::OccReport* rep);
void dgint8_occ_run_12(const dgint8::Args& args, dgint8::OccReport* rep);
void dgint8_occ_run_13(const dgint8::Args& args, dgint8::OccReport* rep);
void dgint8_occ_run_14(const dgint8::Args& args, dgint8::OccReport* rep);
void dgint8_occ_run_15(const dgint8::Args& args, dgint8::OccReport* rep);
void dgint8_occ_run_16(const dgint8::Args& args, dgint8::OccReport* rep);
void dgint8_occ_run_17(const dgint8::Args& args, dgint8::OccReport* rep);
void dgint8_occ_run_18(const dgint8::Args& args, dgint8::OccReport* rep);
static const DgInt8OccCfg kDgInt8OccCfgs[] = {
    {64, 128, 3, 1, 0, 0, 0, 128, 2, 216, 0, 91312, "64x128 s3 c1x1 mt128 occ2 r216"},
    {64, 128, 3, 1, 0, 4096, 4096, 128, 2, 216, 0, 91312, "64x128 s3 c1x1 N4096K4096 mt128 occ2 r216"},
    {64, 128, 3, 1, 0, 4096, 4096, 128, 2, 216, 1, 91312, "64x128 s3 c1x1 N4096K4096 DB mt128 occ2 r216"},
    {64, 128, 3, 2, 0, 4096, 4096, 128, 2, 216, 0, 91312, "64x128 s3 c2x1 N4096K4096 mt128 occ2 r216"},
    {64, 128, 3, 2, 1, 4096, 4096, 128, 2, 216, 0, 91312, "64x128 s3 c1x2 N4096K4096 mt128 occ2 r216"},
    {64, 64, 4, 1, 0, 4096, 4096, 128, 3, 120, 0, 75200, "64x64 s4 c1x1 N4096K4096 mt128 occ3 r120"},
    {64, 64, 6, 1, 0, 4096, 4096, 128, 2, 216, 0, 108512, "64x64 s6 c1x1 N4096K4096 mt128 occ2 r216"},
    {128, 128, 2, 1, 0, 4096, 4096, 128, 2, 216, 0, 99744, "128x128 s2 c1x1 N4096K4096 mt128 occ2 r216"},
    {64, 128, 3, 1, 0, 12288, 4096, 128, 2, 216, 0, 91312, "64x128 s3 c1x1 N12288K4096 mt128 occ2 r216"},
    {64, 128, 3, 1, 0, 4096, 12288, 128, 2, 216, 0, 91312, "64x128 s3 c1x1 N4096K12288 mt128 occ2 r216"},
    {64, 128, 3, 1, 0, 1024, 4096, 128, 2, 216, 0, 91312, "64x128 s3 c1x1 N1024K4096 mt128 occ2 r216"},
    {64, 128, 3, 1, 0, 12288, 4096, 128, 2, 216, 1, 91312, "64x128 s3 c1x1 N12288K4096 DB mt128 occ2 r216"},
    {64, 128, 3, 1, 0, 4096, 12288, 128, 2, 216, 1, 91312, "64x128 s3 c1x1 N4096K12288 DB mt128 occ2 r216"},
    {64, 128, 3, 1, 0, 1024, 4096, 128, 2, 216, 1, 91312, "64x128 s3 c1x1 N1024K4096 DB mt128 occ2 r216"},
    {64, 128, 3, 1, 0, 0, 0, 128, 2, 216, 1, 91312, "64x128 s3 c1x1 DB mt128 occ2 r216"},
    {64, 128, 4, 1, 0, 4096, 4096, 128, 2, 216, 0, 107968, "64x128 s4 c1x1 N4096K4096 halfD mt128 occ2 r216"},
    {64, 128, 4, 1, 0, 4096, 4096, 128, 2, 216, 1, 107968, "64x128 s4 c1x1 N4096K4096 DB halfD mt128 occ2 r216"},
    {64, 128, 4, 2, 0, 4096, 4096, 128, 2, 216, 0, 107968, "64x128 s4 c2x1 N4096K4096 halfD mt128 occ2 r216"},
    {64, 128, 4, 1, 0, 0, 0, 128, 2, 216, 0, 107968, "64x128 s4 c1x1 halfD mt128 occ2 r216"},
};
typedef void (*dgint8_occ_run_fn)(const dgint8::Args&, dgint8::OccReport*);
static const dgint8_occ_run_fn kDgInt8OccRuns[] = {
    dgint8_occ_run_0,
    dgint8_occ_run_1,
    dgint8_occ_run_2,
    dgint8_occ_run_3,
    dgint8_occ_run_4,
    dgint8_occ_run_5,
    dgint8_occ_run_6,
    dgint8_occ_run_7,
    dgint8_occ_run_8,
    dgint8_occ_run_9,
    dgint8_occ_run_10,
    dgint8_occ_run_11,
    dgint8_occ_run_12,
    dgint8_occ_run_13,
    dgint8_occ_run_14,
    dgint8_occ_run_15,
    dgint8_occ_run_16,
    dgint8_occ_run_17,
    dgint8_occ_run_18,
};
static const int kDgInt8OccNumCfgs = 19;
