// generated by pp/gen_pp.py
#pragma once
#include "../dgint8_args.h"
void dgint8_pp_run_0(const dgint8::Args& args);
void dgint8_pp_run_1(const dgint8::Args& args);
void dgint8_pp_run_2(const dgint8::Args& args);
void dgint8_pp_run_3(const dgint8::Args& args);
void dgint8_pp_run_4(const dgint8::Args& args);
void dgint8_pp_run_5(const dgint8::Args& args);
void dgint8_pp_run_6(const dgint8::Args& args);
void dgint8_pp_run_7(const dgint8::Args& args);
void dgint8_pp_run_8(const dgint8::Args& args);
void dgint8_pp_run_9(const dgint8::Args& args);
void dgint8_pp_run_10(const dgint8::Args& args);
void dgint8_pp_run_11(const dgint8::Args& args);
void dgint8_pp_run_12(const dgint8::Args& args);
void dgint8_pp_run_13(const dgint8::Args& args);
void dgint8_pp_run_14(const dgint8::Args& args);
void dgint8_pp_run_15(const dgint8::Args& args);
void dgint8_pp_run_16(const dgint8::Args& args);
void dgint8_pp_run_17(const dgint8::Args& args);
void dgint8_pp_run_18(const dgint8::Args& args);
void dgint8_pp_run_19(const dgint8::Args& args);
void dgint8_pp_run_20(const dgint8::Args& args);
void dgint8_pp_run_21(const dgint8::Args& args);
void dgint8_pp_run_22(const dgint8::Args& args);
void dgint8_pp_run_23(const dgint8::Args& args);
void dgint8_pp_run_24(const dgint8::Args& args);
void dgint8_pp_run_25(const dgint8::Args& args);
void dgint8_pp_run_26(const dgint8::Args& args);
void dgint8_pp_run_27(const dgint8::Args& args);
void dgint8_pp_run_28(const dgint8::Args& args);
void dgint8_pp_run_29(const dgint8::Args& args);
void dgint8_pp_run_30(const dgint8::Args& args);
void dgint8_pp_run_31(const dgint8::Args& args);
static const dgint8::CfgInfo kDgInt8PpCfgs[] = {
    {128, 128, 5, 1, 0, 4096, 4096, 256, 1, "128x128 s5 c1x1 N4096K4096 pp1"},
    {128, 128, 5, 2, 1, 4096, 4096, 256, 1, "128x128 s5 c1x2 N4096K4096 pp1"},
    {128, 128, 5, 1, 0, 4096, 4096, 256, 2, "128x128 s5 c1x1 N4096K4096 pp2"},
    {128, 128, 5, 2, 1, 4096, 4096, 256, 2, "128x128 s5 c1x2 N4096K4096 pp2"},
    {128, 128, 4, 2, 1, 4096, 4096, 256, 1, "128x128 s4 c1x2 N4096K4096 pp1"},
    {256, 128, 3, 2, 1, 4096, 4096, 256, 1, "256x128 s3 c1x2 N4096K4096 pp1"},
    {256, 128, 3, 1, 0, 4096, 4096, 256, 1, "256x128 s3 c1x1 N4096K4096 pp1"},
    {256, 128, 3, 2, 1, 4096, 4096, 256, 2, "256x128 s3 c1x2 N4096K4096 pp2"},
    {128, 128, 5, 2, 1, 4096, 12288, 256, 1, "128x128 s5 c1x2 N4096K12288 pp1"},
    {128, 128, 5, 2, 1, 12288, 4096, 256, 1, "128x128 s5 c1x2 N12288K4096 pp1"},
    {128, 128, 5, 2, 1, 1024, 4096, 256, 1, "128x128 s5 c1x2 N1024K4096 pp1"},
    {256, 128, 3, 2, 1, 4096, 12288, 256, 1, "256x128 s3 c1x2 N4096K12288 pp1"},
    {256, 128, 3, 2, 1, 12288, 4096, 256, 1, "256x128 s3 c1x2 N12288K4096 pp1"},
    {256, 128, 3, 2, 1, 1024, 4096, 256, 1, "256x128 s3 c1x2 N1024K4096 pp1"},
    {128, 128, 5, 1, 0, 0, 0, 256, 1, "128x128 s5 c1x1 pp1"},
    {256, 128, 3, 2, 1, 0, 0, 256, 1, "256x128 s3 c1x2 pp1"},
    {128, 128, 5, 1, 0, 4096, 4096, 256, 5, "128x128 s5 c1x1 N4096K4096 pp5"},
    {128, 128, 5, 2, 1, 4096, 4096, 256, 5, "128x128 s5 c1x2 N4096K4096 pp5"},
    {256, 128, 3, 2, 1, 4096, 4096, 256, 5, "256x128 s3 c1x2 N4096K4096 pp5"},
    {128, 128, 5, 1, 0, 4096, 4096, 256, 6, "128x128 s5 c1x1 N4096K4096 pp6"},
    {256, 128, 3, 2, 1, 4096, 4096, 256, 6, "256x128 s3 c1x2 N4096K4096 pp6"},
    {128, 128, 5, 2, 1, 12288, 4096, 256, 5, "128x128 s5 c1x2 N12288K4096 pp5"},
    {256, 128, 3, 2, 1, 12288, 4096, 256, 5, "256x128 s3 c1x2 N12288K4096 pp5"},
    {128, 128, 5, 1, 0, 0, 0, 256, 5, "128x128 s5 c1x1 pp5"},
    {256, 128, 3, 2, 1, 4096, 12288, 256, 5, "256x128 s3 c1x2 N4096K12288 pp5"},
    {256, 128, 3, 2, 1, 1024, 4096, 256, 5, "256x128 s3 c1x2 N1024K4096 pp5"},
    {256, 128, 3, 2, 1, 0, 0, 256, 6, "256x128 s3 c1x2 pp6"},
    {128, 128, 5, 1, 0, 4096, 4096, 256, 7, "128x128 s5 c1x1 N4096K4096 pp7"},
    {128, 128, 5, 2, 1, 4096, 4096, 256, 7, "128x128 s5 c1x2 N4096K4096 pp7"},
    {128, 128, 5, 2, 1, 12288, 4096, 256, 7, "128x128 s5 c1x2 N12288K4096 pp7"},
    {128, 128, 5, 2, 1, 4096, 12288, 256, 7, "128x128 s5 c1x2 N4096K12288 pp7"},
    {128, 128, 5, 1, 0, 0, 0, 256, 7, "128x128 s5 c1x1 pp7"},
};
typedef void (*dgint8_pp_run_fn)(const dgint8::Args&);
static const dgint8_pp_run_fn kDgInt8PpRuns[] = {
    dgint8_pp_run_0,
    dgint8_pp_run_1,
    dgint8_pp_run_2,
    dgint8_pp_run_3,
    dgint8_pp_run_4,
    dgint8_pp_run_5,
    dgint8_pp_run_6,
    dgint8_pp_run_7,
    dgint8_pp_run_8,
    dgint8_pp_run_9,
    dgint8_pp_run_10,
    dgint8_pp_run_11,
    dgint8_pp_run_12,
    dgint8_pp_run_13,
    dgint8_pp_run_14,
    dgint8_pp_run_15,
    dgint8_pp_run_16,
    dgint8_pp_run_17,
    dgint8_pp_run_18,
    dgint8_pp_run_19,
    dgint8_pp_run_20,
    dgint8_pp_run_21,
    dgint8_pp_run_22,
    dgint8_pp_run_23,
    dgint8_pp_run_24,
    dgint8_pp_run_25,
    dgint8_pp_run_26,
    dgint8_pp_run_27,
    dgint8_pp_run_28,
    dgint8_pp_run_29,
    dgint8_pp_run_30,
    dgint8_pp_run_31,
};
static const int kDgInt8PpNumCfgs = 32;
