"""Config table of the wave-interleave experiment extension (kernels/deepgemm_int8/wi, module deepgemm_int8_wi_ext). Isolated from
the shared gen.py/configs.h so the default cfg ids and the concurrent DB variant are untouched. Fields:
(block_m, block_n, stages, num_tma_multicast, multicast_on_a, compiled N, compiled K, wave_mode) with wave_mode 0 = the unchanged
base kernel (reference instantiations for in-process bit-identity checks), 1 = literal two-wave interleave, 2 = quarter-wave
interleave (see ../gen_kernel_wi.py). Re-run `python gen_wi.py` after editing CONFIGS."""
import os
HERE = os.path.dirname(os.path.abspath(__file__))

CONFIGS = [
    # reference (base kernel, identical to the main extension's cfg ids 8, 11, 10, 9, 12, 0)
    (256, 128, 3, 2, True, 4096, 4096, 0),     # 0: ref 256x128 s3 c1x2 N4096K4096   (main cfg 8)
    (256, 128, 3, 2, True, 4096, 12288, 0),    # 1: ref N4096K12288                  (main cfg 11)
    (256, 128, 3, 2, True, 12288, 4096, 0),    # 2: ref N12288K4096                  (main cfg 10)
    (256, 128, 3, 2, True, 1024, 4096, 0),     # 3: ref N1024K4096                   (main cfg 9)
    (256, 128, 3, 1, False, 4096, 4096, 0),    # 4: ref c1x1 N4096K4096              (main cfg 12)
    (256, 128, 3, 2, True, 0, 0, 0),           # 5: ref dynamic                      (main cfg 0)
    # wave interleave, mode 2 (quarter waves, m64n64k32 groups, 2 x 32 int32 buffers)
    (256, 128, 3, 2, True, 4096, 4096, 2),     # 6: wi2 c1x2 N4096K4096
    (256, 128, 3, 2, True, 4096, 12288, 2),    # 7: wi2 c1x2 N4096K12288
    (256, 128, 3, 2, True, 12288, 4096, 2),    # 8: wi2 c1x2 N12288K4096
    (256, 128, 3, 2, True, 1024, 4096, 2),     # 9: wi2 c1x2 N1024K4096
    (256, 128, 3, 1, False, 4096, 4096, 2),    # 10: wi2 c1x1 N4096K4096
    (256, 128, 3, 2, True, 4096, 4096, 1),     # 11: wi1 literal two-wave interleave (2 x 64 int32 live -> spills; evidence only)
    (256, 128, 3, 2, True, 0, 0, 2),           # 12: wi2 c1x2 dynamic (K = 128 / 256 edge cases)
]

def rows():
    out = []
    for i, (bm, bn, st, mc, on_a, sn, sk, wm) in enumerate(CONFIGS):
        name = (f"{bm}x{bn} s{st} c{'1x2' if (mc == 2 and on_a) else '2x1' if mc == 2 else '1x1'}" + (f" N{sn}K{sk}" if sn or sk else "")
                + (f" wi{wm}" if wm else " ref"))
        out.append(dict(i=i, bm=bm, bn=bn, st=st, mc=mc, on_a=on_a, sn=sn, sk=sk, wm=wm, mt=256, name=name))
    return out

def main():
    rs = rows()
    for r in rs:
        tmpl = f"{r['sn']}u, {r['sk']}u, {r['bm']}u, {r['bn']}u, {r['st']}u, {r['mc']}u, {'true' if r['on_a'] else 'false'}"
        body = (f"    dgint8::launch_wi<{tmpl}, {r['wm']}u>(args);\n" if r['wm'] else f"    dgint8::launch<{tmpl}>(args);\n")
        open(os.path.join(HERE, f"wicfg_{r['i']:02d}.cu"), "w").write(
            '// generated by wi/gen_wi.py -- one kernel instantiation per translation unit\n'
            + ('#include "../launcher_wi.cuh"\n' if r['wm'] else '#include "../launcher.cuh"\n')
            + f"void dgint8_wi_run_{r['i']}(const dgint8::Args& args) {{\n" + body + "}\n")
    for f in os.listdir(HERE):
        if f.startswith("wicfg_") and f.endswith(".cu") and int(f[6:8]) >= len(rs):
            os.remove(os.path.join(HERE, f))
    with open(os.path.join(HERE, "wi_configs.h"), "w") as f:
        f.write('// generated by wi/gen_wi.py\n#pragma once\n#include "../dgint8_args.h"\n')
        for r in rs:
            f.write(f"void dgint8_wi_run_{r['i']}(const dgint8::Args& args);\n")
        f.write("static const dgint8::CfgInfo kDgInt8WiCfgs[] = {\n")
        for r in rs:
            f.write(f"    {{{r['bm']}, {r['bn']}, {r['st']}, {r['mc']}, {int(r['on_a'])}, {r['sn']}, {r['sk']}, {r['mt']}, {r['wm']}, \"{r['name']}\"}},\n")
        f.write("};\ntypedef void (*dgint8_wi_run_fn)(const dgint8::Args&);\nstatic const dgint8_wi_run_fn kDgInt8WiRuns[] = {\n")
        for r in rs:
            f.write(f"    dgint8_wi_run_{r['i']},\n")
        f.write("};\n")
        f.write(f"static const int kDgInt8WiNumCfgs = {len(rs)};\n")
    print("\n".join(f"wi cfg {r['i']}: {r['name']}" for r in rs))

if __name__ == "__main__":
    main()
