// generated by wi/gen_wi.py
#pragma once
#include "../dgint8_args.h"
void dgint8_wi_run_0(const dgint8::Args& args);
void dgint8_wi_run_1(const dgint8::Args& args);
void dgint8_wi_run_2(const dgint8::Args& args);
void dgint8_wi_run_3(const dgint8::Args& args);
void dgint8_wi_run_4(const dgint8::Args& args);
void dgint8_wi_run_5(const dgint8::Args& args);
void dgint8_wi_run_6(const dgint8::Args& args);
void dgint8_wi_run_7(const dgint8::Args& args);
void dgint8_wi_run_8(const dgint8::Args& args);
void dgint8_wi_run_9(const dgint8::Args& args);
void dgint8_wi_run_10(const dgint8::Args& args);
void dgint8_wi_run_11(const dgint8::Args& args);
void dgint8_wi_run_12(const dgint8::Args& args);
static const dgint8::CfgInfo kDgInt8WiCfgs[] = {
    {256, 128, 3, 2, 1, 4096, 4096, 256, 0, "256x128 s3 c1x2 N4096K4096 ref"},
    {256, 128, 3, 2, 1, 4096, 12288, 256, 0, "256x128 s3 c1x2 N4096K12288 ref"},
    {256, 128, 3, 2, 1, 12288, 4096, 256, 0, "256x128 s3 c1x2 N12288K4096 ref"},
    {256, 128, 3, 2, 1, 1024, 4096, 256, 0, "256x128 s3 c1x2 N1024K4096 ref"},
    {256, 128, 3, 1, 0, 4096, 4096, 256, 0, "256x128 s3 c1x1 N4096K4096 ref"},
    {256, 128, 3, 2, 1, 0, 0, 256, 0, "256x128 s3 c1x2 ref"},
    {256, 128, 3, 2, 1, 4096, 4096, 256, 2, "256x128 s3 c1x2 N4096K4096 wi2"},
    {256, 128, 3, 2, 1, 4096, 12288, 256, 2, "256x128 s3 c1x2 N4096K12288 wi2"},
    {256, 128, 3, 2, 1, 12288, 4096, 256, 2, "256x128 s3 c1x2 N12288K4096 wi2"},
    {256, 128, 3, 2, 1, 1024, 4096, 256, 2, "256x128 s3 c1x2 N1024K4096 wi2"},
    {256, 128, 3, 1, 0, 4096, 4096, 256, 2, "256x128 s3 c1x1 N4096K4096 wi2"},
    {256, 128, 3, 2, 1, 4096, 4096, 256, 1, "256x128 s3 c1x2 N4096K4096 wi1"},
    {256, 128, 3, 2, 1, 0, 0, 256, 2, "256x128 s3 c1x2 wi2"},
};
typedef void (*dgint8_wi_run_fn)(const dgint8::Args&);
static const dgint8_wi_run_fn kDgInt8WiRuns[] = {
    dgint8_wi_run_0,
    dgint8_wi_run_1,
    dgint8_wi_run_2,
    dgint8_wi_run_3,
    dgint8_wi_run_4,
    dgint8_wi_run_5,
    dgint8_wi_run_6,
    dgint8_wi_run_7,
    dgint8_wi_run_8,
    dgint8_wi_run_9,
    dgint8_wi_run_10,
    dgint8_wi_run_11,
    dgint8_wi_run_12,
};
static const int kDgInt8WiNumCfgs = 13;
